services:
  domesticas-api:
    build: .
    container_name: domesticas-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      DB_USER: postgres.ilqaxhnpzvyszcuxwauc
      DB_PASSWORD: Domesticas123*+
      JWT_SECRET: mi_clave_super_secreta_para_jwt_12345678901234567890
      PORT: 8080